spring:
  application:
    name: smart-billing-platform
  datasource:
    url: jdbc:sqlite:billing_platform.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect

management:
  endpoints:
    web:
      base-path: "/manage"

